-- 지수 정보 (Index_Infos)
CREATE TABLE index_infos (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- int64
    index_classification    VARCHAR(255),               -- string
    index_name              VARCHAR(255) NOT NULL,      -- string
    employed_items_count    INTEGER,                    -- int32
    base_point_in_time      DATE,                       -- date
    base_index              NUMERIC(20, 4),             -- number (정밀도 유지용)
    source_type             VARCHAR(100),               -- string
    favorite                BOOLEAN DEFAULT FALSE       -- boolean
);

-- 지수 데이터 (Index_Data)
-- 대용량 + 시계열 특성 → FK 없음 (논리적 FK만 유지)
CREATE TABLE index_data (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- int64
    index_info_id           BIGINT NOT NULL,            -- FK
    base_date               DATE NOT NULL,              -- date
    source_type             VARCHAR(100),               -- string
    market_price            NUMERIC(20, 4),             -- number
    closing_price           NUMERIC(20, 4),             -- number
    high_price              NUMERIC(20, 4),             -- number
    low_price               NUMERIC(20, 4),             -- number
    versus                  NUMERIC(20, 4),             -- number
    fluctuation_rate        NUMERIC(10, 4),             -- number
    trading_quantity        BIGINT,                     -- int64
    trading_price           BIGINT,                     -- int64 (정수 단위 가격)
    market_total_amount     BIGINT,                      -- int64 (총액, 정수형)
    CONSTRAINT fk_index_data_index
        FOREIGN KEY (index_info_id)
            REFERENCES index_infos (id)
            ON DELETE CASCADE
);

-- 지수 연동 (Sync_Jobs)
CREATE TABLE sync_jobs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,             -- int64
    index_info_id   BIGINT NOT NULL,                   -- FK 유지
    job_type        VARCHAR(100) NOT NULL,
    target_date     DATE,
    worker          VARCHAR(100),
    job_time        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    result          BOOLEAN,
    CONSTRAINT fk_sync_jobs_index
       FOREIGN KEY (index_info_id)
           REFERENCES index_infos (id)
           ON DELETE CASCADE
);

-- 자동 연동 (Auto_Sync)
CREATE TABLE auto_sync (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,             -- int64
    index_info_id BIGINT NOT NULL,
    enabled         BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_auto_sync_index
       FOREIGN KEY (index_info_id)
           REFERENCES index_infos (id)
           ON DELETE CASCADE
);